version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: filerun
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
    ports:
      - "8009:8009"
    container_name: filerun_app_proxy

  filerun:
    image: filerun/filerun:8.1
    container_name: filerun
    volumes:
      - ${APP_DATA_DIR}/user-files:/user-files
      - ${APP_DATA_DIR}/html:/var/www/html
    ports:
      - 80
